'use strict';
const DATA=window.TEST_DATA,VOCAB=window.VOCAB_DATA,Q=DATA.questions,KEY='field-notes-g6-phrases-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s??'').normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?;:，。！？；：]/g,'').replace(/\s+/g,' ').trim();
const blankCount=q=>q.options?0:q.answer[0].trim().split(/\s+/).length;
const answerValue=a=>Array.isArray(a)?a.join(' '):a;
function answerParts(q,a){const n=blankCount(q);if(Array.isArray(a))return Array.from({length:n},(_,i)=>a[i]??'');let text=String(a??'').trim();const alias=q.answer.find(v=>normalize(v)===normalize(text));if(alias&&text.split(/\s+/).length!==n)text=q.answer[0];const words=text?text.split(/\s+/):[];return Array.from({length:n},(_,i)=>i===n-1?words.slice(i).join(' '):words[i]||'')}
const filled=(q,a)=>q.options?Number.isInteger(a):answerParts(q,a).every(w=>w.trim()&&!/\s/.test(w.trim()));
const isAnswered=(id,a)=>filled(Q.find(q=>q.id===id),a);
const isCorrect=(q,a)=>q.options?Number.isInteger(a)&&a===q.answer:(!Array.isArray(a)||filled(q,a))&&q.answer.some(v=>normalize(v)===normalize(answerValue(a)));
const answered=a=>Array.isArray(a)?a.some(w=>w.trim()):a!==undefined&&a!==null&&String(a).trim()!=='';
const ids=new Set(Q.map(q=>q.id));
const validAnswer=(id,a)=>{const q=Q.find(q=>q.id===id);return q&&(q.options?Number.isInteger(a)&&a>=0&&a<q.options.length:(typeof a==='string'&&a.length<=1000||Array.isArray(a)&&a.length===blankCount(q)&&a.every(w=>typeof w==='string'&&w.length<=1000)))};
const cleanAnswers=x=>Object.fromEntries(Object.entries(x&&typeof x==='object'?x:{}).filter(([id,a])=>validAnswer(id,a)));
function initial(){return{draft:null,history:[],mistakes:{}}}
function cleanState(raw){
 if(!raw||typeof raw!=='object')throw Error('invalid');const state=initial();
 if(raw.draft&&typeof raw.draft==='object'){
 const d=raw.draft,qs=Array.isArray(d.ids)?[...new Set(d.ids.filter(id=>ids.has(id)))]:[];
 if(qs.length&&['exam','review','practice'].includes(d.mode))state.draft={ids:qs,mode:d.mode,answers:cleanAnswers(d.answers),flags:Array.isArray(d.flags)?d.flags.filter(id=>ids.has(id)):[],index:Math.min(Math.max(Number.isInteger(d.index)?d.index:0,0),qs.length-1),started:Number.isFinite(d.started)?Math.min(Date.now(),Math.max(0,d.started)):Date.now()};
 }
 if(Array.isArray(raw.history))state.history=raw.history.slice(0,50).filter(h=>h&&Array.isArray(h.ids)&&h.ids.some(id=>ids.has(id))).map(h=>({id:String(h.id||Date.now()).slice(0,80),date:Number.isFinite(h.date)?h.date:Date.now(),elapsed:Number.isFinite(h.elapsed)?Math.max(0,h.elapsed):0,mode:['review','practice'].includes(h.mode)?h.mode:'exam',ids:[...new Set(h.ids.filter(id=>ids.has(id)))],answers:cleanAnswers(h.answers)}));
 if(raw.mistakes&&typeof raw.mistakes==='object')for(const [id,m] of Object.entries(raw.mistakes))if(ids.has(id)&&m&&typeof m==='object')state.mistakes[id]={times:Math.max(1,Math.min(9999,Number(m.times)||1)),last:Number.isFinite(m.last)?m.last:Date.now(),lastAnswer:validAnswer(id,m.lastAnswer)?m.lastAnswer:null,mastered:m.mastered===true};
 return state;
}
let state=initial(),storageOK=true;try{const raw=localStorage.getItem(KEY);if(raw)state=cleanState(JSON.parse(raw))}catch(e){storageOK=false}
let reportId=state.history[0]?.id,reviewFilter='all',mistakeFilter='active',vocabUnit=0,search='',confirmAction=null;
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch(e){storageOK=false;toast('浏览器未能保存记录，请及时导出备份。')}updateBadge()}
function updateBadge(){$('#mistake-count').textContent=Object.values(state.mistakes).filter(m=>!m.mastered).length}
function confirmBox(title,text,button,action,cancel='继续作答'){confirmAction=action;$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;$('#accept-confirm').textContent=button;$('#cancel-confirm').textContent=cancel;$('#confirm').showModal()}
$('#cancel-confirm').onclick=()=>$('#confirm').close();$('#accept-confirm').onclick=()=>{$('#confirm').close();const action=confirmAction;confirmAction=null;action?.()};
function go(route){if(location.hash==='#'+route)render();else location.hash=route}
function duration(ms){const n=Math.floor(ms/1000);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function dateText(ms){return new Date(ms).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function art(){return `<div class="study-art" aria-label="英语在线测试流程笔记插画" role="img"><div class="art-grid"></div><div class="paper-back"></div><div class="paper-note"><span class="note-eyebrow">MY ENGLISH NOTEBOOK</span><h2>Small words.<br>Big ideas.</h2><div class="note-rule"></div><div class="note-row"><span>01</span><b>Listen</b></div><div class="note-row"><span>02</span><b>Choose</b></div><div class="note-row"><span>03</span><b>Complete</b></div><div class="note-row"><span>04</span><b>Review</b></div><div class="hand-check">✓ Learn it. Use it.</div></div><div class="sticky-note"><span>UNIT 1 — UNIT 6</span><b>Words<br>together.</b><small>听得懂 · 写得对 · 用得出</small></div><div class="pencil"></div></div>`}
function home(){const draft=state.draft;return `<section class="hero"><div><div class="eyebrow">UNIT 01–06 / 固定搭配专题</div><h1>Words into<br><em>practice.</em></h1><p class="subtitle">从记住单词，到真正会用。</p><p class="description">把零散单词连成准确的表达。围绕购物、观点、自然、发明、健康与旅行，练习介词、动词搭配和完整短语。</p><div class="hero-actions"><button class="btn" data-action="${draft?'resume':'start'}">${draft?'继续未完成的答题':'开始固定搭配练习'} <span>↗</span></button><a class="btn secondary" href="#mistakes">复习错题 <span>→</span></a></div><p class="hero-caption">${draft?`已保存 ${draft.ids.filter(id=>isAnswered(id,draft.answers[id])).length} / ${draft.ids.length} 题 · 可随时续答`:'整卷在线作答 · 30 道选择题 + 30 道填空题'}</p></div>${art()}</section><div class="stats"><div class="stat"><strong>${Q.length}</strong><span>道在线试题</span></div><div class="stat"><strong>120</strong><span>分综合评估</span></div><div class="stat"><strong>${DATA.minutes}</strong><span>分钟建议用时</span></div><div class="stat"><strong>60</strong><span>组搭配与表达</span></div></div><div class="scope-strip"><b>当前范围：Unit 1–6</b><span>原词表短语 + 相关常用搭配</span></div><div class="section-heading"><h2>六个单元，系统练习<small>也可按单元练习</small></h2><span>LISTEN · SPELL · APPLY</span></div><div class="module-grid">${DATA.sections.map((s,i)=>{const items=Q.filter(q=>q.section===s.id);return `<article class="module"><span class="num">0${i+1}</span><div><small>${s.en}</small><h3>${s.name}</h3><p>${items.length} 题 · ${items.reduce((n,q)=>n+q.points,0)} 分</p><p>${s.focus}</p><button class="practice-link" data-practice="${s.id}">开始专项练习 →</button></div></article>`}).join('')}</div><div class="home-bottom"><div class="audio-check"><button class="play-circle" data-action="sound" aria-label="播放听力试听">▶</button><div><b>先试试你的耳机</b><span>微软神经语音 · 英式英语 · 可重复播放</span></div><audio id="intro-audio" preload="none" src="audio/intro.mp3"></audio></div><p class="notice">依据你提供的完整六单元词表编写，包含原表短语及相关常用搭配；搭配清单中标注来源。采用校内阶段练习取向，未套用某一学校真卷。每小题全对得分，不倒扣分；计时仅供参考。答案与解析在交卷后显示。</p></div>`}

function start(mode='exam',chosen=Q.map(q=>q.id)){
 const begin=()=>{state.draft={mode,ids:chosen,answers:{},flags:[],index:0,started:Date.now()};save();go('exam')};
 if(state.draft)confirmBox('开始一轮新练习？','当前未交卷的进度将被替换；已提交的成绩和错题仍会保留。','开始新练习',begin,'保留当前进度');else begin();
}
function passage(q){return q.section==='read'?`<section class="passage"><h3>A JOURNEY TO AUSTRALIA / 短文综合填空</h3><p>${esc(DATA.reading)}</p></section>`:''}
function audioBox(clip){return `<div class="audio-box"><div class="audio-title"><span>◉ 听力材料 ${clip.slice(1)} · Microsoft Sonia</span><label>播放速度 <select class="speed" aria-label="音频播放速度"><option value="1">标准</option><option value="0.85">0.85×</option><option value="1.15">1.15×</option></select></label></div><audio controls preload="metadata" src="audio/${clip}.mp3" aria-label="听力材料 ${clip.slice(1)}"></audio><p class="audio-error" hidden>音频加载失败，请确认 audio 文件夹已一并部署，然后刷新重试。</p></div>`}
function paperQuestion(q,d){
 const n=d.ids.indexOf(q.id)+1,id=q.id,flagged=d.flags.includes(id),a=d.answers[id];
 const input=q.options?'':`<span class="word-blanks" role="group" aria-label="第 ${n} 题答案">${answerParts(q,a).map((word,i)=>`<input class="answer-input paper-input word-input" data-answer-id="${id}" data-blank-index="${i}" aria-label="第 ${n} 题第 ${i+1} 空" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="1000" enterkeyhint="next" value="${esc(word)}">`).join('')}</span>`;
 let stem=esc(q.prompt);
 if(!q.options){const blank=/_{2,}(?:\s+_{2,})*/;stem=blank.test(stem)?stem.replace(blank,()=>input):stem+`<span class="dictation-space">${input}</span>`}
 return `<article class="paper-question ${filled(q,a)?'is-answered':''}" id="item-${id}" data-question="${id}"><div class="paper-question-head"><span class="paper-number">${n}.</span><span class="paper-kind">${q.options?'选择题':'填空题'} · ${q.points} 分</span>${q.clip?`<button class="paper-audio-link" data-audio-jump="${q.clip}">听力材料 ↗</button>`:''}<button class="paper-flag ${flagged?'on':''}" data-flag-id="${id}" aria-label="标记第 ${n} 题" aria-pressed="${flagged}">${flagged?'⚑ 已标记':'⚑'}</button></div><div class="paper-stem" id="stem-${id}">${stem}</div>${q.options?`<div class="paper-options" role="radiogroup" aria-labelledby="stem-${id}">${q.options.map((o,i)=>`<label class="option ${a===i?'selected':''}"><input type="radio" name="answer-${id}" data-answer-id="${id}" value="${i}" ${a===i?'checked':''}><span class="letter">${'ABCD'[i]}.</span><span>${esc(o)}</span></label>`).join('')}</div>`:''}</article>`;
}
function exam(){const d=state.draft;if(!d)return `<div class="empty"><h2>Unit 1–6 固定搭配试卷</h2><p>60 题 · 满分 120 分</p><button class="btn" data-action="start">开始作答</button></div>`;
 const current=d.ids.map(id=>Q.find(q=>q.id===id)),sections=DATA.sections.filter(s=>current.some(q=>q.section===s.id)),done=current.filter(q=>isAnswered(q.id,d.answers[q.id])).length,max=current.reduce((n,q)=>n+q.points,0),mode=d.mode==='exam'?'六年级英语固定搭配专题练习':d.mode==='review'?'六年级英语错题重练':'六年级英语专项练习';
 return `<div class="paper-tools"><div class="paper-tools-row"><a class="paper-back-link" href="#home" aria-label="返回首页">← <span>试卷</span></a><span class="paper-progress"><b id="progress-text">${done} / ${current.length}</b><small>已作答</small></span><span id="timer" class="paper-timer">${duration(Date.now()-d.started)}<small>已用时间</small></span><button class="paper-tool-btn" data-action="unanswered">检查未答</button><details class="paper-map"><summary>答题卡</summary><div class="paper-map-panel"><div class="question-map">${d.ids.map((id,i)=>`<button class="map-btn ${isAnswered(id,d.answers[id])?'answered':''} ${d.flags.includes(id)?'flagged':''}" data-index="${i}" aria-label="第 ${i+1} 题">${i+1}</button>`).join('')}</div><p>绿色：已答　橙点：标记</p></div></details><button class="paper-tool-btn submit-link" data-action="paper-end">前往交卷 ↓</button></div><nav class="paper-tabs" aria-label="试卷大题">${sections.map((s,i)=>`<button data-section="${s.id}">${['一','二','三','四','五','六'][i]}、${s.name}</button>`).join('')}</nav><div class="progress-track"><span id="progress-bar" style="width:${done/current.length*100}%"></span></div></div><div class="exam-paper"><header class="paper-title"><p>PRIMARY ENGLISH · UNIT 1–6 · COLLOCATIONS</p><h1>${mode}</h1><div class="paper-meta"><span>范围：Unit 1–6</span><span>满分：${max} 分</span><span>共 ${current.length} 题</span>${d.mode==='exam'?`<span>建议用时：${DATA.minutes} 分钟</span>`:''}</div><div class="paper-score-table"><table><thead><tr><th scope="col">大题</th>${sections.map((s,i)=>`<th scope="col">${['一','二','三','四','五','六'][i]}</th>`).join('')}<th scope="col">总分</th></tr></thead><tbody><tr><th scope="row">满分</th>${sections.map(s=>`<td>${current.filter(q=>q.section===s.id).reduce((n,q)=>n+q.points,0)}</td>`).join('')}<td>${max}</td></tr></tbody></table></div></header>${sections.map((s,i)=>{const qs=current.filter(q=>q.section===s.id),seen=new Set();return `<section class="paper-section" id="section-${s.id}" aria-labelledby="section-title-${s.id}"><h2 id="section-title-${s.id}">${['一','二','三','四','五','六'][i]}、${s.name}<span>（共 ${qs.length} 题，每题 2 分，共 ${qs.length*2} 分）</span></h2>${s.id==='read'?passage(qs[0]):''}${qs.map(q=>{let audio='';if(q.clip&&!seen.has(q.clip)){seen.add(q.clip);const nums=qs.filter(x=>x.clip===q.clip).map(x=>d.ids.indexOf(x.id)+1);audio=`<div class="paper-audio" id="paper-audio-${q.clip}"><span class="audio-question-range">第 ${nums.join('、')} 题</span>${audioBox(q.clip)}</div>`}return audio+paperQuestion(q,d)}).join('')}</section>`}).join('')}<footer class="paper-end" id="paper-end"><span>— 本卷结束 —</span><div><p>已作答 <b id="end-progress">${done} / ${current.length}</b></p><button class="btn secondary" data-action="unanswered">检查未答</button><button class="btn" data-action="submit">交卷并查看成绩</button></div><small id="paper-save-status">${storageOK?'答题进度已自动保存':'进度暂未保存，请导出备份'}</small></footer></div>`;
}
function setAnswer(a,id){const d=state.draft;if(!d||!d.ids.includes(id))return;d.answers[id]=a;d.index=d.ids.indexOf(id);save();const done=d.ids.filter(id=>isAnswered(id,d.answers[id])).length;$('#progress-text').textContent=`${done} / ${d.ids.length}`;$('#end-progress').textContent=`${done} / ${d.ids.length}`;$('#progress-bar').style.width=done/d.ids.length*100+'%';document.querySelectorAll('.map-btn').forEach((b,i)=>b.classList.toggle('answered',isAnswered(d.ids[i],d.answers[d.ids[i]])));const article=document.getElementById('item-'+id);article.classList.toggle('is-answered',isAnswered(id,a));article.querySelectorAll('.option').forEach(l=>l.classList.toggle('selected',l.querySelector('input').checked));$('#paper-save-status').textContent=storageOK?'答题进度已自动保存':'进度暂未保存，请导出备份'}
function jump(index,focus=false){const d=state.draft;if(!d||index<0||index>=d.ids.length)return;d.index=index;save();document.querySelector('.paper-map')?.removeAttribute('open');const item=document.getElementById('item-'+d.ids[index]);if(!item)return;item.scrollIntoView({block:'start',behavior:'instant'});if(focus)(Array.from(item.querySelectorAll('input')).find(el=>el.type!=='radio'&&!el.value.trim())||item.querySelector('input'))?.focus({preventScroll:true});document.querySelectorAll('.jump-target').forEach(el=>el.classList.remove('jump-target'));void item.offsetWidth;item.classList.add('jump-target')}
function jumpUnanswered(){const d=state.draft;if(!d)return;const at=d.ids.findIndex(id=>!isAnswered(id,d.answers[id]));if(at<0){toast('所有题目均已作答');$('#paper-end')?.scrollIntoView({block:'center'})}else jump(at,true)}
function submit(){const d=state.draft;if(!d)return;const left=d.ids.filter(id=>!isAnswered(id,d.answers[id])).length,flagged=d.flags.length;confirmBox('确认提交本轮答题？',`${left?`还有 ${left} 题未作答，未答题计 0 分。`:'所有题目已作答。'}${flagged?`另有 ${flagged} 题标记待检查。`:''}交卷后会显示分数、正确答案与逐题解析。`,'确认交卷',()=>{
 const h={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),date:Date.now(),elapsed:Date.now()-d.started,mode:d.mode,ids:[...d.ids],answers:{...d.answers}};
 for(const id of d.ids){const q=Q.find(q=>q.id===id),old=state.mistakes[id];if(!isCorrect(q,d.answers[id]))state.mistakes[id]={times:(old?.times||0)+1,last:Date.now(),lastAnswer:d.answers[id]??null,mastered:false};else if(old)old.mastered=true}
 state.history.unshift(h);state.history=state.history.slice(0,50);state.draft=null;reportId=h.id;reviewFilter='all';save();go('report');
 })}
function score(h){return h.ids.reduce((n,id)=>{const q=Q.find(q=>q.id===id);return n+(isCorrect(q,h.answers[id])?q.points:0)},0)}
function total(h){return h.ids.reduce((n,id)=>n+Q.find(q=>q.id===id).points,0)}
function answerText(q,a){return !answered(a)?'未作答':q.options?`${'ABCD'[a]}. ${q.options[a]}`:Array.isArray(a)?a.map(w=>w.trim()||'____').join(' '):String(a)}
function rightText(q){return q.options?`${'ABCD'[q.answer]}. ${q.options[q.answer]}`:q.answer[0]}
function reviewCard(q,a,extra=''){const good=isCorrect(q,a);return `<article class="review-card"><div class="q-meta"><span>${DATA.sections.find(s=>s.id===q.section).name} · 原卷第 ${Q.indexOf(q)+1} 题</span><span class="result-tag ${good?'':'bad'}">${good?'答对':'需巩固'}</span><span>${good?q.points:0} / ${q.points} 分</span>${extra}</div><h3>${esc(q.prompt)}</h3>${q.options?`<div class="review-options">${q.options.map((o,i)=>`${'ABCD'[i]}. ${esc(o)}`).join('<br>')}</div>`:''}<div class="answer-row"><b>你的答案</b>${esc(answerText(q,a))}</div><div class="answer-row"><b>参考答案</b>${esc(rightText(q))}</div><p class="explanation">${esc(q.explanation)}</p>${q.clip?`<details><summary>听力原文与音频</summary>${audioBox(q.clip)}<p class="transcript">${esc(DATA.clips[q.clip])}</p></details>`:passage(q)?`<details><summary>查看原文材料</summary>${passage(q)}</details>`:''}</article>`}
function report(){const h=state.history.find(h=>h.id===reportId)||state.history[0];if(!h)return `<div class="empty"><h2>还没有已提交的测试</h2><a class="btn" href="#home">开始挑战</a></div>`;reportId=h.id;const points=score(h),max=total(h),wrong=h.ids.filter(id=>!isCorrect(Q.find(q=>q.id===id),h.answers[id])),percent=points/max;
 return `<div class="eyebrow">YOUR FIELD REPORT / ${h.mode==='review'?'错题重练报告':h.mode==='practice'?'专项练习报告':'阶段综合练习报告'}</div><h1 class="page-title">每一次复盘，都是进步。</h1><p class="page-desc">${dateText(h.date)} · 用时 ${duration(h.elapsed)} · 答对 ${h.ids.length-wrong.length} / ${h.ids.length} 题</p><section class="summary"><div class="score">${points}<small> / ${max}</small></div><div><h2>${percent>=.9?'词汇运用，掌握得很扎实':percent>=.75?'你已掌握大部分考点':percent>=.6?'基础正在稳步建立':'从错题里找到下一步'}</h2><p>${wrong.length?`${wrong.length} 道错题（含未答题）已自动加入错题本，重练答对后归入已掌握。`:'本轮全部答对。试着向家人讲清每道题的理由吧。'}</p><div class="score-grid">${DATA.sections.map(s=>{const qs=h.ids.map(id=>Q.find(q=>q.id===id)).filter(q=>q.section===s.id);return qs.length?`<span>${s.name}<b>${qs.reduce((n,q)=>n+(isCorrect(q,h.answers[q.id])?q.points:0),0)} / ${qs.reduce((n,q)=>n+q.points,0)}</b></span>`:''}).join('')}</div></div></section><div class="toolbar"><button class="btn small" data-action="retry-report" ${wrong.length?'':'disabled'}>重练本轮错题</button><button class="btn secondary small" data-action="start">再做一遍全卷</button><button class="btn secondary small" data-action="export-report">导出本次报告</button><button class="filter ${reviewFilter==='all'?'active':''}" data-review-filter="all">全部题目</button><button class="filter ${reviewFilter==='wrong'?'active':''}" data-review-filter="wrong">只看错题 (${wrong.length})</button></div>${h.ids.filter(id=>reviewFilter==='all'||wrong.includes(id)).map(id=>reviewCard(Q.find(q=>q.id===id),h.answers[id])).join('')||'<div class="empty"><h2>本轮没有错题</h2></div>'}`;
}
function mistakes(){const entries=Object.entries(state.mistakes).filter(([id,m])=>mistakeFilter==='all'||(mistakeFilter==='active'?!m.mastered:m.mastered)),active=Object.keys(state.mistakes).filter(id=>!state.mistakes[id].mastered);return `<div class="eyebrow">YOUR LEARNING JOURNAL</div><h1 class="page-title">错题，是下一次进步的起点。</h1><p class="page-desc">记录每次失误，也记录每次掌握。重练答对后自动归入「已掌握」；以后再答错会回到待巩固。数据保存在此浏览器，可导出后在其他设备导入。</p><div class="toolbar"><button class="btn small" data-action="review-active" ${active.length?'':'disabled'}>重练待巩固 (${active.length})</button><button class="btn secondary small" data-action="export">导出学习备份</button><label class="btn secondary small import-label">导入备份<input type="file" id="import-file" accept=".json,application/json" class="visually-hidden"></label></div><div class="toolbar">${[['active','待巩固'],['mastered','已掌握'],['all','全部']].map(([v,n])=>`<button class="filter ${mistakeFilter===v?'active':''}" data-mistake-filter="${v}">${n}</button>`).join('')}</div>${entries.length?entries.map(([id,m])=>{const q=Q.find(q=>q.id===id);return `<article class="review-card"><div class="q-meta"><span>${DATA.sections.find(s=>s.id===q.section).name} · 第 ${Q.indexOf(q)+1} 题</span><span class="result-tag ${m.mastered?'':'bad'}">${m.mastered?'已掌握':'待巩固'}</span><span>累计错 ${m.times} 次</span></div><h3>${esc(q.prompt)}</h3><p class="notice">最近错误：${dateText(m.last)}</p><div class="toolbar" style="margin-bottom:0"><button class="btn secondary small" data-retry="${id}">重练此题 →</button></div><details><summary>查看上次答案与解析</summary><div class="answer-row">上次答案：${esc(answerText(q,m.lastAnswer))}</div><div class="answer-row">参考答案：${esc(rightText(q))}</div><p class="explanation">${esc(q.explanation)}</p>${q.clip?audioBox(q.clip)+`<p class="transcript">${esc(DATA.clips[q.clip])}</p>`:passage(q)}</details></article>`}).join(''):`<div class="empty"><div class="symbol">↟</div><h2>${mistakeFilter==='mastered'?'等待第一次突破':'这里暂时没有错题'}</h2><p>${mistakeFilter==='mastered'?'完成错题重练，答对的题目会出现在这里。':'提交测试后，错题会自动记录在这里。'}</p><a class="btn" href="#home">回到阶段练习</a></div>`}`}
function wordCards(){const filtered=DATA.phrases.filter(p=>(!vocabUnit||p.unit===vocabUnit)&&normalize(p.phrase+' '+p.meaning).includes(normalize(search)));return `<p class="notice" style="margin-bottom:16px">找到 ${filtered.length} 组搭配与表达</p><div class="word-grid">${filtered.map(p=>`<article class="word"><p class="unit-label">UNIT ${p.unit} · ${p.origin}</p><h3>${esc(p.phrase)}</h3><p class="meaning">${esc(p.meaning)}</p><p class="phrase-note">${esc(p.note)}</p><button class="practice-link" data-phrase-practice="${Q.find(q=>q.phraseId===p.id).id}">练这一组 →</button></article>`).join('')}</div>${filtered.length?'':'<p class="empty">没有匹配的搭配，请换个关键词。</p>'}`}
function vocab(){return `<div class="eyebrow">WORDS THAT GO TOGETHER / UNIT 1–6</div><h1 class="page-title">记住搭配，才能用准单词。</h1><p class="page-desc">60 组搭配与表达，覆盖原词表明确列出的全部多词短语，并补充六个单元词汇的常用搭配。「原词表」表示直接来自你提供的词表；「词汇拓展」表示相关常用表达，不代表已核对教材全文。sb 表示某人，sth 表示某物，do 表示动词原形，doing 表示动词 -ing 形式。</p><div class="toolbar"><label class="visually-hidden" for="word-search">搜索搭配或中文</label><input id="word-search" class="search" placeholder="搜索搭配 / 中文释义" value="${esc(search)}"><button class="btn secondary small" data-action="download-phrases">下载搭配清单</button><button class="btn secondary small" data-action="download-vocab">下载完整词库</button></div><div class="toolbar">${[0,1,2,3,4,5,6].map(n=>`<button class="filter ${vocabUnit===n?'active':''}" data-unit="${n}">${n?'Unit '+n:'全部搭配'}</button>`).join('')}</div><div id="word-results">${wordCards()}</div>`}
function history(){return `<div class="eyebrow">ONE STEP AT A TIME</div><h1 class="page-title">看见你的每一点进步。</h1><p class="page-desc">保留最近 50 次提交，包括整卷测试、专项练习与错题重练。学习备份同时包含未交卷进度、成绩记录和错题本。</p><div class="toolbar"><button class="btn secondary small" data-action="export">导出学习备份</button><label class="btn secondary small import-label">导入备份<input type="file" id="import-file" accept=".json,application/json" class="visually-hidden"></label></div>${state.history.length?state.history.map(h=>`<article class="history-row"><div><b>${h.mode==='exam'?'Unit 1–6 固定搭配专题':h.mode==='practice'?'Unit 1–6 专项练习':'Unit 1–6 错题重练'}</b><p>${dateText(h.date)} · ${h.ids.length} 题 · 用时 ${duration(h.elapsed)}</p></div><strong>${score(h)}<small style="font-size:14px;color:var(--muted)"> / ${total(h)}</small></strong><button class="btn secondary small" data-report="${esc(h.id)}">查看报告 →</button></article>`).join(''):'<div class="empty"><div class="symbol">↗</div><h2>第一次挑战，从现在开始。</h2><p>完成测试后，你的成绩会自动保存在这里。</p><a class="btn" href="#home">开始阶段练习</a></div>'}`}
function render(){const route=location.hash.slice(1)||'home';document.body.classList.toggle('paper-mode',route==='exam');$('#app').innerHTML=({home,exam,report,mistakes,vocab,history}[route]||home)();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route||(a.dataset.nav==='home'&&['exam','report'].includes(route))));updateBadge();document.querySelectorAll('audio').forEach(a=>{a.addEventListener('error',()=>{const msg=a.parentElement.querySelector('.audio-error');if(msg)msg.hidden=false;else toast('试听音频加载失败，请检查 audio 文件夹。')});a.addEventListener('play',()=>document.querySelectorAll('audio').forEach(other=>{if(other!==a)other.pause()}))})}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportBackup(){download('原野英语-Unit1-6固定搭配学习备份-'+new Date().toISOString().slice(0,10)+'.json',{format:KEY,exportedAt:Date.now(),data:state})}
function exportReport(){const h=state.history.find(h=>h.id===reportId);if(!h)return;download('Unit1-6固定搭配-答题报告.txt',`Unit 1–6 固定搭配专题\n${dateText(h.date)}\n成绩：${score(h)} / ${total(h)}\n用时：${duration(h.elapsed)}\n\n`+h.ids.map(id=>{const q=Q.find(q=>q.id===id);return `第 ${Q.indexOf(q)+1} 题 ${q.prompt}\n${q.options?q.options.map((o,i)=>'ABCD'[i]+'. '+o).join('\n')+'\n':''}你的答案：${answerText(q,h.answers[id])}\n参考答案：${rightText(q)}\n得分：${isCorrect(q,h.answers[id])?q.points:0}/${q.points}\n解析：${q.explanation}${q.clip?'\n听力原文：'+DATA.clips[q.clip]:''}`}).join('\n\n'),'text/plain;charset=utf-8')}
async function importBackup(file){if(!file)return;try{if(file.size>3*1024*1024)throw Error();const raw=JSON.parse(await file.text());if(raw.format!==KEY||!raw.data||!Array.isArray(raw.data.history)||!raw.data.mistakes||typeof raw.data.mistakes!=='object')throw Error();const candidate=cleanState(raw.data);confirmBox('导入学习备份？',`将用此备份替换当前浏览器的学习记录。备份含 ${candidate.history.length} 次提交、${Object.keys(candidate.mistakes).length} 道错题。建议先导出当前记录。`,'确认导入',()=>{state=candidate;reportId=state.history[0]?.id;save();render();toast('学习备份已导入')},'取消')}catch(e){toast('无法导入：请使用本应用导出的有效 JSON 备份。')}}
$('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=state.draft;
 if(b.dataset.phrasePractice){start('practice',[b.dataset.phrasePractice]);return}if(b.dataset.audioJump){document.getElementById('paper-audio-'+b.dataset.audioJump)?.scrollIntoView({block:'start'});return}if(b.dataset.flagId){const id=b.dataset.flagId;d.flags=d.flags.includes(id)?d.flags.filter(x=>x!==id):[...d.flags,id];save();b.classList.toggle('on',d.flags.includes(id));b.setAttribute('aria-pressed',String(d.flags.includes(id)));b.textContent=d.flags.includes(id)?'⚑ 已标记':'⚑';document.querySelectorAll('.map-btn').forEach((el,i)=>el.classList.toggle('flagged',d.flags.includes(d.ids[i])));return}if(b.dataset.practice){start('practice',Q.filter(q=>q.section===b.dataset.practice).map(q=>q.id));return}if(b.dataset.index!==undefined){jump(Number(b.dataset.index));return}if(b.dataset.section){d.index=d.ids.findIndex(id=>Q.find(q=>q.id===id).section===b.dataset.section);save();document.querySelector('.paper-map')?.removeAttribute('open');document.getElementById('section-'+b.dataset.section)?.scrollIntoView({block:'start'});return}if(b.dataset.reviewFilter){reviewFilter=b.dataset.reviewFilter;render();return}if(b.dataset.mistakeFilter){mistakeFilter=b.dataset.mistakeFilter;render();return}if(b.dataset.unit!==undefined){vocabUnit=Number(b.dataset.unit);render();return}if(b.dataset.report){reportId=b.dataset.report;reviewFilter='all';go('report');return}if(b.dataset.retry){start('review',[b.dataset.retry]);return}
 switch(b.dataset.action){case 'unanswered':jumpUnanswered();break;case 'paper-end':$('#paper-end')?.scrollIntoView({block:'center'});break;case 'start':start();break;case 'resume':go('exam');break;case 'prev':jump(Math.max(0,d.index-1));break;case 'next':jump(Math.min(d.ids.length-1,d.index+1));break;case 'flag':{const id=d.ids[d.index];d.flags=d.flags.includes(id)?d.flags.filter(x=>x!==id):[...d.flags,id];save();render();break}case 'submit':submit();break;case 'review-active':start('review',Q.filter(q=>state.mistakes[q.id]&&!state.mistakes[q.id].mastered).map(q=>q.id));break;case 'retry-report':{const h=state.history.find(h=>h.id===reportId);start('review',h.ids.filter(id=>!isCorrect(Q.find(q=>q.id===id),h.answers[id])));break}case 'export':exportBackup();break;case 'export-report':exportReport();break;case 'download-phrases':download('六年级上册-固定搭配清单.json',DATA.phrases);break;case 'download-vocab':download('外研版六上-完整词库.json',VOCAB);break;case 'sound':{const a=$('#intro-audio');if(a.paused){a.play().then(()=>{b.textContent='Ⅱ'}).catch(()=>toast('未能播放试听，请检查音频文件或浏览器声音设置。'));a.onended=()=>b.textContent='▶'}else{a.pause();b.textContent='▶'}break}}
});
$('#app').addEventListener('input',e=>{if(e.target.matches('.answer-input')){const el=e.target,id=el.dataset.answerId;const fields=Array.from(el.closest('.word-blanks').querySelectorAll('input'));setAnswer(fields.map(f=>f.value),id);}if(e.target.id==='word-search'){search=e.target.value;$('#word-results').innerHTML=wordCards()}});
$('#app').addEventListener('paste',e=>{const el=e.target;if(!el.matches('.answer-input'))return;const words=e.clipboardData.getData('text').trim().split(/\s+/),fields=Array.from(el.closest('.word-blanks').querySelectorAll('input')),at=Number(el.dataset.blankIndex);if(words.length<2||fields.length===1)return;e.preventDefault();for(let i=at;i<fields.length;i++)fields[i].value=i===fields.length-1?words.slice(i-at).join(' '):words[i-at]||'';setAnswer(fields.map(f=>f.value),el.dataset.answerId);fields[Math.min(at+words.length-1,fields.length-1)].focus()});
$('#app').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing&&e.target.matches('.answer-input')&&state.draft){e.preventDefault();const d=state.draft;const index=d.ids.indexOf(e.target.dataset.answerId);const fields=Array.from(e.target.closest('.word-blanks').querySelectorAll('input')),next=fields[Number(e.target.dataset.blankIndex)+1];if(next){next.focus();return}if(index===d.ids.length-1){e.target.blur();$('#paper-end')?.scrollIntoView({block:'center'})}else jump(index+1,true)}});
$('#app').addEventListener('change',e=>{if(e.target.matches('input[type="radio"][data-answer-id]'))setAnswer(Number(e.target.value),e.target.dataset.answerId);if(e.target.matches('.speed'))e.target.closest('.audio-box').querySelector('audio').playbackRate=Number(e.target.value);if(e.target.id==='import-file')importBackup(e.target.files[0])});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});setInterval(()=>{if($('#timer')&&state.draft)$('#timer').innerHTML=`${duration(Date.now()-state.draft.started)}<small>已用时间 · ${Date.now()-state.draft.started>DATA.minutes*60000?'已超过建议用时，可继续作答':'不自动交卷'}</small>`},1000);
render();if(location.hash==='#exam'&&state.draft?.index>0)requestAnimationFrame(()=>jump(state.draft.index));if(!storageOK)setTimeout(()=>toast('浏览器存储不可用或记录读取失败，请导出备份以免丢失进度。'),400);
